---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    run: hello
  name: hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: hello
        ports:
        - containerPort: 80
          protocol: TCP
